project:
  type: website

website:
  title: "The Harry Simms Fund for Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: mastodon
        href: https://union.place/home

page-footer: 
    left: "Copyright 2025, The Harry Simms Fund" 
    right: 
      - icon: envelope
        href: mailto:info@harrysimmsfund.org
        text: Contact Us

format:
  html:
    theme:
      light: yeti
      dark: darkly
      
    css: styles.css
    toc: true

editor: visual

