project:
  type: website

website:
  title: "The Harry Simms Fund for Education"
  navbar:
    left:
      - about.qmd
      - href: https://linksta.cc/@HSF
        text: Social Media ![](/linkstacc.png){height=1.5em}
  
  page-footer: 
    left: "Copyright 2025, The Harry Simms Fund" 
    right:    
      - href: mailto:info@harrysimmsfund.org
        text: Contact Us
        icon: envelope

format:
  html:
    theme:
      light: flatly
      dark: darkly
      
    css: styles.css
    toc: false

editor: visual

