project:
  type: website

website:
  title: "The Harry Simms Fund for Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: mastodon
        href: https://union.place/@harrysimmsfund
        text: Mastodon
  
  page-footer: 
    left: "Copyright 2025, The Harry Simms Fund" 
    right:    
      - href: mailto:info@harrysimmsfund.org
        text: Contact Us
        icon: envelope

format:
  html:
    theme:
      light: flatly
      dark: darkly
      
    css: styles.css
    toc: false

editor: visual

